# Generated by Django 4.0.6 on 2022-07-28 12:17

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=django_editorjs.fields.EditorJsField(default=3),
            preserve_default=False,
        ),
    ]
