# Generated by Django 4.0.6 on 2022-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_message_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
    ]
