# Generated by Django 4.0.6 on 2022-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_user_dribble_user_facebook_user_twitter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dribble',
            new_name='dribbble',
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
