# Generated by Django 4.0.6 on 2022-07-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
    ]
