# Generated by Django 4.0.6 on 2022-07-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
