# Generated by Django 4.0.6 on 2022-07-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comment_body_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
    ]
