# Generated by Django 4.0.6 on 2022-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
